# Generated by Django 4.2.30 on 2026-04-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CE', 'CE'), ('eu_cosmetics', 'EU Cosmetics'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_de', models.CharField(blank=True, max_length=200)),
                ('description_ar', models.TextField()),
                ('description_en', models.TextField()),
                ('description_de', models.TextField(blank=True)),
                ('marketing_desc_ar', models.TextField(blank=True)),
                ('marketing_desc_en', models.TextField(blank=True)),
                ('marketing_desc_de', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('unit_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('units_per_carton', models.IntegerField(blank=True, null=True)),
                ('carton_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('carton_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carton_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carton_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_care_label', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awaiting_seller_shipment', 'Awaiting Seller Shipment'), ('in_warehouse_egypt', 'In Warehouse Egypt'), ('in_transit', 'In Transit'), ('in_warehouse_germany', 'In Warehouse Germany'), ('listed', 'Listed')], default='draft', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('shopify_product_id', models.CharField(blank=True, max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity_submitted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('discount_percent', 'Discount Percent'), ('discount_fixed', 'Discount Fixed'), ('bundle', 'Bundle')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
            ],
        ),
    ]
