# Generated by Django 4.2.30 on 2026-05-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='external_barcode',
            field=models.CharField(blank=True, help_text='EAN-13, UPC, أو أي كود خارجي للبائع', max_length=50),
        ),
    ]
