# Generated by Django 4.2.30 on 2026-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_external_barcode_update_sku_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
