# Generated by Django 4.2.30 on 2026-05-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_previous_status_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
