# Generated by Django 4.2.30 on 2026-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_code_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_specs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
