# Generated by Django 4.2.30 on 2026-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_model_number_custom_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
