# Generated by Django 4.2.30 on 2026-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sku_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
