# Generated by Django 4.2.30 on 2026-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_production_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awaiting_seller_shipment', 'Awaiting Seller Shipment'), ('in_warehouse_egypt', 'In Warehouse Egypt'), ('in_transit', 'In Transit'), ('in_warehouse_germany', 'In Warehouse Germany'), ('listed', 'Listed'), ('suspended', 'Suspended')], default='draft', max_length=30),
        ),
    ]
