# Generated by Django 4.2.30 on 2026-06-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_inner_height_cm_product_inner_length_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(),
        ),
    ]
