# Generated by Django 4.2.30 on 2026-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
