# Generated by Django 4.2.30 on 2026-04-24 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellertier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerpromotion',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_promotions', to='sellers.promotion'),
        ),
        migrations.AddField(
            model_name='sellerpromotion',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='sellers.sellertier'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerdocument',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='target_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='sellers.sellertier'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerpromotion',
            unique_together={('seller', 'promotion')},
        ),
    ]
