# Generated by Django 4.2.30 on 2026-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
