# Generated by Django 4.2.30 on 2026-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_sellerprofile_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='commercial_register_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='legal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='legal_company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
