# Generated by Django 4.2.30 on 2026-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_sellerprofile_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
