# Generated by Django 4.2.30 on 2026-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_registration_fee', models.DecimalField(decimal_places=2, default=39.99, max_digits=8)),
                ('product_listing_fee', models.DecimalField(decimal_places=2, default=2.0, max_digits=8)),
                ('storage_fee_per_cbm', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
                ('pick_pack_fee', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('commission_wikala', models.DecimalField(decimal_places=2, default=0.15, max_digits=5)),
                ('commission_external', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(choices=[('wikala', 'Wikala'), ('external', 'External')], default='wikala', max_length=10)),
                ('quantity_sold', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pick_pack_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('external_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]
