# Generated by Django 4.2.30 on 2026-04-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('sellers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerstatement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_records', to='finance.sellerstatement'),
        ),
    ]
