# Generated by Django 4.2.30 on 2026-05-31 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_suspended_status_execution_status'),
        ('finance', '0003_webservice_webservicecharge_sellerdiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='level',
            field=models.CharField(choices=[('seller', 'Seller Level'), ('product', 'Product Level')], default='seller', max_length=10),
        ),
        migrations.AddField(
            model_name='webservicecharge',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_charges', to='products.product'),
        ),
    ]
