# Generated by Django 4.2.30 on 2026-06-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_status'),
        ('finance', '0004_webservice_level_webservicecharge_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='product',
        ),
        migrations.AddField(
            model_name='salerecord',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='products.productvariant'),
            preserve_default=False,
        ),
    ]
