# Generated by Django 4.2.30 on 2026-06-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_salerecord_product_salerecord_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerstatement',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerstatement',
            name='auto_finalize_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerstatement',
            name='overall_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerstatement',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerstatement',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerstatement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sellerstatement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('disputed', 'Disputed'), ('paid', 'Paid')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='StatementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('sale', 'Sale'), ('commission', 'Commission'), ('storage', 'Storage Fee'), ('shipping', 'Shipping Fee'), ('pick_pack', 'Pick & Pack'), ('web_service', 'Web Service'), ('custom', 'Custom Charge')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.sellerstatement')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatementDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_message', models.TextField()),
                ('admin_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='finance.statementlineitem')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='finance.sellerstatement')),
            ],
        ),
    ]
