# Generated by Django 4.2.30 on 2026-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_sellerstatement_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerstatement',
            name='discount_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
