# Generated by Django 4.2.30 on 2026-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_sellerstatement_discount_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementlineitem',
            name='item_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('vat', 'VAT'), ('commission', 'Commission'), ('storage', 'Storage Fee'), ('shipping', 'Shipping Fee'), ('pick_pack', 'Pick & Pack'), ('web_service', 'Web Service'), ('custom', 'Custom Charge')], max_length=20),
        ),
    ]
