# Generated by Django 4.2.30 on 2026-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_statementlineitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementlineitem',
            name='item_type',
            field=models.CharField(max_length=50),
        ),
    ]
