# Generated by Django 4.2.30 on 2026-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_statementlineitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementlineitem',
            name='reference_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
