# Generated by Django 4.2.30 on 2026-05-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
        ('products', '0007_sku_nullable'),
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('requested_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('pickup', 'Pickup by Wikala'), ('courier', 'Courier'), ('drop_off', 'Drop Off at Wikala')], max_length=20)),
                ('delivery_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_requests', to='sellers.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartons_count', models.IntegerField()),
                ('units_per_carton', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=0)),
                ('carton_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('carton_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carton_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carton_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='products.product')),
                ('shipment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shipmentrequest')),
            ],
        ),
    ]
