# Generated by Django 4.2.30 on 2026-05-14 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shipmentrequest_shipmentrequestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentrequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
