# Generated by Django 4.2.30 on 2026-05-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_shipment_request_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantinventory',
            name='arrived_germany_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
