# Generated by Django 4.2.30 on 2026-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_arrived_germany_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentrequest',
            name='execution_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('issue', 'Issue')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='issue_note',
            field=models.TextField(blank=True),
        ),
    ]
