# Generated by Django 4.2.30 on 2026-06-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_status'),
        ('inventory', '0007_add_suspended_status_execution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentrequestitem',
            name='product',
        ),
        migrations.AddField(
            model_name='shipmentrequestitem',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='products.productvariant'),
            preserve_default=False,
        ),
    ]
