# Generated by Django 4.2.30 on 2026-08-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_shipmentrequestitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
