# Generated by Django 4.2.30 on 2026-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_variantinventory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantinventory',
            name='bin_location_egypt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='variantinventory',
            name='bin_location_germany',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
