# Generated by Django 4.2.30 on 2026-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('shipment_updated', 'Shipment Updated'), ('message_received', 'Message Received'), ('issue_updated', 'Issue Updated'), ('statement_ready', 'Statement Ready'), ('seller_approved', 'Seller Approved'), ('seller_rejected', 'Seller Rejected'), ('unmatched_sale', 'Unmatched Sale')], max_length=30),
        ),
    ]
